### PR TITLE
New functionality: Update translations

### PR DESCRIPTION
**Pull request by jhholm**
This pull request contains the following changes

* Adds crossenv to support development in Windows
* Moved @types dependencies to devDependencies
* Added dependencies that are used, but not mentioned in package.json - makes this work with pnpm if needed
* Fixes popup to work in incognito and private browser - wrapped fetch calls in chrome.scripting.executescript
  *  Actions pivot used to be grayed out when in incognito
* New functionality - update translations for a site page

There is a bug within SharePoint that I've had to use PnP JS console to fix for a long time. Technically it's possible that the data in search, item level and translations api can get out of sync, and you get duplicated entries in news web parts on translated pages. Checked that the Translations functionality in SharePoint itself uses this same API from time to time if do you happen funny stuff.

### CODE REVIEW

**Comment by jhholm** [comment]
Cleanup, also added the message to show if this is not supported

**Comment by jhholm** [comment]
image
Supported, no need to fix anything, everything seems to be in sync

**Comment by jhholm** [comment]
image
Not supported, you get an error message

**Comment by tavikukko** [comment]
Fantastic! Just updated the master branch with 7.1.0 release and we have conflict. If you could check the conflict in package.json file and then we can merge this. Thanks so much @jhholm !

**Comment by jhholm** [comment]
Okay. I should be able to use my changes. I added some dependencies that were used in the code, but not mentioned in package.json. This is not kosher when using pnpm. Also moved some types from dependencies to devDependencies.

But I also want to clean up the error and success messages very quickly. I'll update soon.

**Comment by jhholm** [comment]
Did some additional refactoring and updated dependencies. Should not have any conflicts anymore. Note that I moved some @types from dependencies to devDependencies

**Pull request merged**
